### ISSUE TITLE
naiveproxy docker example

### ISSUE THREAD

**Issue by Ah5hM82kK** [klzgrad/naiveproxy#101]
Very thanks for rnaiveproxy let us could across gfw

Dockerfile

```Dockerfile
FROM alpine:latest
LABEL maintainer="AH5H"

ENV NAIVEPROXY_VERSION=v84.0.4147.89-1
ENV NAIVEPROXY_HOME="/usr/local/bin/naive"
ENV NAIVEPROXY_RM="naiveproxy-${NAIVEPROXY_VERSION}-openwrt-x86_64"
ENV FILE="${NAIVEPROXY_RM}.tar.xz"

RUN set -xe \
  && apk add --no-cache --virtual libnss3 curl nss\
  && mkdir -p "$NAIVEPROXY_HOME" \
  && cd "$NAIVEPROXY_HOME"\
  && curl -fsSLO --compressed "https://github.com/klzgrad/naiveproxy/releases/download/${NAIVEPROXY_VERSION}/${FILE}" \
  && tar xJvf "${FILE}" -C "$NAIVEPROXY_HOME" \
  && ls -al \
  && mv ${NAIVEPROXY_HOME}/${NAIVEPROXY_RM}/* ${NAIVEPROXY_HOME} \
  && rm -rf "${NAIVEPROXY_HOME}/${FILE}" "${NAIVEPROXY_HOME}/${NAIVEPROXY_RM}" LICENSE USAGE.txt \
  && adduser -D naiveproxy_user

COPY config.json "${NAIVEPROXY_HOME}/config.json"
COPY entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh

RUN echo "export NAIVEPROXY_HOME=${NAIVEPROXY_HOME}" >> /etc/profile
VOLUME "$NAIVEPROXY_HOME"

USER naiveproxy_user
ENTRYPOINT [ "/entrypoint.sh" ]
```

entrypoint.sh

```sh
#!/bin/sh
COMMAND=$NAIVEPROXY_HOME/naive

DEFAULT_ARGS=" $NAIVEPROXY_HOME/config.json"

if [ "$1" = "--help" ]; then
    set -- $COMMAND --help
else
    set -- $COMMAND $DEFAULT_ARGS $@
fi
``
exec "$@"
```

config.json

```json
{
  "listen": "socks://127.0.0.1:1080",
  "proxy": "https://username:password@example.com",
   "log":""
}
```

**Comment by Ah5hM82kK** [comment]
docker-compose.yml

```yml
version: '2.1'

services:

  naiveproxy:
    build:
      context: ./docker
    container_name: naiveproxy
    restart: always
    volumes:
      - "./config.json:/usr/local/bin/naive/config.json"
```

**Comment by Ah5hM82kK** [comment]
caddy 

Dockerfile

```Dockerfile
FROM golang:1.14-alpine as builder
LABEL maintainer="AH5H"

WORKDIR /home

RUN set -xe \
  && apk add --no-cache git \
  && git clone -b naive https://github.com/klzgrad/forwardproxy \
  && git clone -b master https://github.com/caddy-dns/cloudflare \
  && go get -u github.com/caddyserver/xcaddy/cmd/xcaddy \
  && /go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=/home/forwardproxy \
  --with github.com/caddy-dns/cloudflare=/home/cloudflare

FROM alpine:3.12

RUN apk add --no-cache ca-certificates mailcap

RUN set -eux; \
	mkdir -p \
		/config/caddy \
		/data/caddy \
		/etc/caddy \
		/usr/share/caddy ;

COPY ./config.json /etc/caddy/config.json
COPY ./index.html /usr/share/caddy/index.html
COPY --from=builder /home/caddy /usr/bin/caddy

RUN set -eux; \
	chmod +x /usr/bin/caddy; \
	caddy version

RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf

ENV XDG_CONFIG_HOME=/config
ENV XDG_DATA_HOME=/data

VOLUME /config
VOLUME /data

EXPOSE 80
EXPOSE 443

WORKDIR /srv

CMD ["caddy", "run", "--config", "/etc/caddy/config.json"]
```

index.html

```html
HELLO WORLD
```

config.json

```json
{
	"apps": {
		"http": {
			"servers": {
				"srv0": {
					"listen": [
						":80"
					],
					"routes": [
						{
							"handle": [
								{
									"handler": "vars",
									"root": "/usr/share/caddy"
								},
								{
									"handler": "file_server",
									"hide": [
										"./Caddyfile"
									]
								}
							]
						}
					]
				}
			}
		}
	}
}
```

**Comment by Ah5hM82kK** [comment]
docker-compose.yml

```yml
version: '2.1'

services:
  caddy:
    build:
      context: ./docker
    container_name: caddy
    restart: always
    volumes:
      - "./config.json:/etc/caddy/config.json"
      - "./www:/www"
      - "./data:/data"
    ports:
      - 80:80
      - 443:443
```
