### ISSUE TITLE
如果不使用naiveproxy作为客户端，此时含有forwardproxy模块的服务端是否相当于一个普通的https代理服务器？

### ISSUE THREAD

**Issue by giveup** [klzgrad/naiveproxy#739]
我尝试使用clash作为客户端，clash没有明确提到是否支持naiveproxy，但是配置http却能正常连接。
 伪配置如下
```yaml
proxies:
- name: "http"
  type: http
  server: server
  port: 443
  username: username
  password: password
  tls: true
  skip-cert-verify: true
  alpn:
    - h2
    - http/1.1
    - h3
```
是否如同[wiki](https://github.com/klzgrad/naiveproxy/wiki/%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9A%84http2%E4%BB%A3%E7%90%86)所说，此时只能使用到naiveproxy 80%的功能。
